name: master
on:
  push:
    branches:
      - master

jobs:
  release:
    name: CI/CD
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          ./integ-tests/run.sh
      - name: Release
        run: |
          pip install virtualenv==20.0.14
          virtualenv --python python3 .aws-cdk-lambdecor-release
          source ./.aws-cdk-lambdecor-release/bin/activate
          pip install -r test-requirements.txt
          pyci release --repo iliapolo/aws-cdk-lambdecor --branch master --no-binary
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
