name: Continuous Release
on:
  push:
    branches:
      - master

jobs:
  integ:
    name: Integration
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          ./integ-tests/run.sh
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: python:3.6.12-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: |
          pip install -r test-requirements.txt
          pyci release
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
